version: '3.8'

services:
  php:
    build: .
    container_name: php8.3
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - my_xdebug_net

  apache:
    image: httpd:2.4
    container_name: apache_php8
    ports:
      - "8081:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - my_xdebug_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_xdebug_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - my_xdebug_net

volumes:
  mysql_data:

networks:
  my_xdebug_net:
    external: true
